using System;
using System.Collections.Generic;
using System.IO;
using System.Net;
using System.Text;
using System.Text.Json.Nodes;
using NATS.NKeys.Benchmarks;
using Xunit;
using Xunit.Abstractions;

namespace NATS.NKeys.Tests;

public class NKeysTest(ITestOutputHelper output)
{
    public static IEnumerable<object[]> PrefixData
    {
        get
        {
            yield return [PrefixByte.User, 'U'];
            yield return [PrefixByte.Account, 'A'];
            yield return [PrefixByte.Operator, 'O'];
            yield return [PrefixByte.Cluster, 'C'];
            yield return [PrefixByte.Server, 'N'];
        }
    }

    [Fact]
    public void XKey_from_seed()
    {
        var kp = KeyPair.FromSeed("SXALBV3GJABONHXVSTRWL2NXYVUF5LY66CGVF4INX2XBMMVYT2KCZXRXWA".ToCharArray());
        Assert.Equal("XBKXUQXILUXDDHTWEDECINN24IUYFQAYG737MB5PMEAVMUMHCIWRA3UD", kp.GetPublicKey());
        var exception = Assert.Throws<NKeysException>(() => kp.Sign(default, default));
        Assert.Equal("Invalid curve key operation", exception.Message);

        var exception2 = Assert.Throws<NKeysException>(() => kp.Verify(default, default));
        Assert.Equal("Invalid curve key operation", exception2.Message);
    }

    [Fact]
    public void XKey_seal_open_compare_to_Go_nkeys_library()
    {
        // Read test data generated by Go nkeys library
        var json = JsonNode.Parse(File.ReadAllText("test_data.json"));
        foreach (var data in json!["xkeys"]!.AsArray())
        {
            var seed1 = data!["seed1"]!.GetValue<string>();
            var pk1 = data!["pk1"]!.GetValue<string>();
            var seed2 = data!["seed2"]!.GetValue<string>();
            var pk2 = data!["pk2"]!.GetValue<string>();
            var text1 = data!["text"]!.GetValue<string>();
            var cypherText = data!["cypher_text"]!.GetValue<string>();
            var openText = data!["open_text"]!.GetValue<string>();

            var kp1 = KeyPair.FromSeed(seed1.ToCharArray());
            var kp2 = KeyPair.FromSeed(seed2.ToCharArray());

            // Double check data
            Assert.Equal(text1, openText);
            Assert.Equal(pk1, kp1.GetPublicKey());
            Assert.Equal(pk2, kp2.GetPublicKey());

            // Open cipher sealed by Go nkeys library
            var open2 = kp2.Open(Convert.FromBase64String(cypherText), pk1);
            var text2 = Convert.ToBase64String(open2);
            Assert.Equal(text1, text2);

            // Double check seal since we can't compare sealed data since
            // it'd be different every time because of nonce
            var seal = kp1.Seal(Convert.FromBase64String(text1), pk2);
            var open3 = kp2.Open(seal, pk1);
            var text3 = Convert.ToBase64String(open3);
            Assert.Equal(text1, text3);
        }
    }

    [Fact]
    public void XKey_seal_open()
    {
        var kp1 = KeyPair.FromSeed("SXAD4F52S2XAJTJ3TGDJ4VXQVW7TU35XJUSVKF25ZRXIWCIUK6NLANRHVY".ToCharArray());
        var pk1 = kp1.GetPublicKey();
        output.WriteLine($"pk1: {pk1}");

        var kp2 = KeyPair.FromSeed("SXAAPCLFDKJ3FOGPXVS5OT3ZRYT5CZHVRRJUEZKHHJNFQQI5IURJ3IN3OU".ToCharArray());
        var pk2 = kp2.GetPublicKey();
        output.WriteLine($"pk2: {pk2}");

        var seal = kp1.Seal(Encoding.UTF8.GetBytes("hello"), pk2);

        var seal64 = Convert.ToBase64String(seal);
        output.WriteLine($"seal64: {seal64}");

        foreach (var sealed64Text in new[]
                 {
                     seal64,

                     // generated using nkeys Go library:
                     "eGt2MchZLvgdJ5IKV4ZD/pAHnpwGMw2D2j7eA/vjRBhZzWmQAvbTzMTu8M1aevP4Gg==",
                     "eGt2MRpP/wq2ckUO5PMs8ao4EB2Vrb6uMdxspLnxsqQXT7HUoYk/WdhK49WVVbK70w==",
                     "eGt2MZ0ka1T50jsi8YcP/xYRW+gG/Cg0Mufkmlo7bpOHrCHEvkOmaRcIJ6xzpFtqww==",
                     "eGt2MUNXS9+hvSaH5uTWJ5xpDNJuGCfBUxTKm4BD9OdoPkYNEiv9mr63dUZTjcdmNQ==",
                     "eGt2MUNTNs7wYhKx9wJ+k/YXOAEhbrqHsRQXZpMb5WXtMqFxkDj7S1iRSCJme0Eubg==",
                     "eGt2Mekw7+a2WRuMxGVtRU7dAEg0iYqTtRiei0w+nUXwdKbWgtkCgJV4rlMXJycL+Q==",
                     "eGt2MSpwx9uW1pbYUFGPdfQ45sASe/mvUtSfXidTi92tr6YXzaq2dHnE5xr2qLDxuw==",
                 })
        {
            var open = kp2.Open(Convert.FromBase64String(sealed64Text), pk1);
            var text = Encoding.UTF8.GetString(open);
            Assert.Equal("hello", text);
            output.WriteLine($"open: {text}");
        }
    }

    [Fact]
    public void XKey_create()
    {
        var kp = KeyPair.CreatePair(PrefixByte.Curve, new FixedRng());
        Assert.Equal("SXAD4F52S2XAJTJ3TGDJ4VXQVW7TU35XJUSVKF25ZRXIWCIUK6NLANRHVY", kp.GetSeed());
        Assert.Equal("XDS6PE7IMMUA7XXUZLWQIPUCRS3J2IGXVMI3ZEOWX7LY4IMBPH2XECZM", kp.GetPublicKey());
        var exception = Assert.Throws<NKeysException>(() => kp.Sign(default, default));
        Assert.Equal("Invalid curve key operation", exception.Message);
    }

    [MemberData(nameof(PrefixData))]
    [Theory]
    public void Create_key_pair(PrefixByte prefix, char initial)
    {
        var pair = KeyPair.CreatePair(prefix);
        Assert.NotNull(pair);
        Assert.NotEmpty(pair.GetSeed());
        Assert.NotEmpty(pair.GetPublicKey());
        Assert.Equal(initial, pair.GetPublicKey()[0]);
        Assert.Equal($"S{initial}", pair.GetSeed().Substring(0, 2));

        var signature = new Memory<byte>(new byte[64]);
        var message = new ReadOnlyMemory<byte>([1, 2]);
        var corrupt = new ReadOnlyMemory<byte>([1, 2, 3]);
        pair.Sign(message, signature);
        Assert.True(pair.Verify(message, signature));
        Assert.False(pair.Verify(corrupt, signature));

        // check against reference implementations
        var pair1Seed = NKeysReference1.FromEncodedSeed(pair.GetSeed());
        var signature1 = NKeysReference1.Sign(pair1Seed, message.ToArray());
        Assert.Equal(signature.Span.ToArray(), signature1);
        Assert.True(NKeysReference1.VerifyUsingSeed(pair1Seed, message.ToArray(), signature.ToArray()));
        Assert.True(NKeysReference1.VerifyUsingSeed(pair1Seed, message.ToArray(), signature1));
        Assert.False(NKeysReference1.VerifyUsingSeed(pair1Seed, corrupt.ToArray(), signature1));

        var pair2 = NKeysUtilsReference2.FromSeed(pair.GetSeed());
        var signature2 = pair2.Sign(message.ToArray());
        Assert.Equal(signature.Span.ToArray(), signature2);
    }

    [MemberData(nameof(PrefixData))]
    [Theory]
    public void Create_with_rng(PrefixByte prefix, char initial)
    {
        var rng = new FixedRng();

        var pair = KeyPair.CreatePair(prefix, rng);
        var seed = pair.GetSeed();
        var pub = pair.GetPublicKey();

        var sk = NKeysReference1.NewSeed(rng);

        output.WriteLine($"seed: {NKeysReference1.GetEncodedSeed(initial, sk)}");
        output.WriteLine($"seed: {seed}");
        Assert.Equal(NKeysReference1.GetEncodedSeed(initial, sk), seed);

        output.WriteLine($"public: {NKeysReference1.GetEncodedPublicKey(initial, sk)}");
        output.WriteLine($"public: {pub}");
        Assert.Equal(NKeysReference1.GetEncodedPublicKey(initial, sk), pub);

        Assert.Equal('S', seed[0]);
        Assert.Equal(initial, seed[1]);
        Assert.Equal(initial, pub[0]);
    }

    [MemberData(nameof(PrefixData))]
    [Theory]
    public void Create_seed_for_prefix(PrefixByte prefix, char initial)
    {
        var kp = KeyPair.CreatePair(prefix);
        Assert.NotEmpty(kp.GetSeed());
        Assert.False(kp.GetSeed().EndsWith("=", StringComparison.Ordinal));
        Assert.Equal(initial, kp.GetPublicKey()[0]);
    }

    [Fact]
    public void Public_key_from_seed()
    {
        // using nsc generated seeds for testing
        var kp = KeyPair.FromSeed("SOAELH6NJCEK4HST5644G4HK7TOAFZGRRJHNM4EUKUY7PPNDLIKO5IH4JM".ToCharArray());
        Assert.Equal("ODPWIBQJVIQ42462QAFI2RKJC4RZHCQSIVPRDDHWFCJAP52NRZK6Z2YC", kp.GetPublicKey());

        kp = KeyPair.FromSeed("SAANWFZ3JINNPERWT3ALE45U7GYT2ZDW6GJUIVPDKUF6GKAX6AISZJMAS4".ToCharArray());
        Assert.Equal("AATEJXG7UX4HFJ6ZPRTP22P6OYZER36YYD3GVBOVW7QHLU32P4QFFTZJ", kp.GetPublicKey());

        kp = KeyPair.FromSeed("SUAGDLNBWI2SGHDRYBHD63NH5FGZSVJUW2J7GAJZXWANQFLDW6G5SXZESU".ToCharArray());
        Assert.Equal("UBICBTHDKQRB4LIYA6BMIJ7EA2G7YS7FIWMMVKZJE6M3HS5IVCOLKDY2", kp.GetPublicKey());

        kp = KeyPair.FromSeed("SXANLPW5OPP62ISXMPTH26DBYM4BGT3U6P2FEALGW3BZAVXQRWCX3KH2ZM".ToCharArray());
        Assert.Equal("XBIGHMCJSHWYFW6ZY4WWONQ3FRIS5A3OQAUMPPKYBNKRYQTVX4PEAIZA", kp.GetPublicKey());
    }

    [Fact]
    public void Api()
    {
        var kp1 = KeyPair.CreatePair(PrefixByte.User);
        var seed = kp1.GetSeed();
        var publicKey = kp1.GetPublicKey();
        output.WriteLine($"seed={seed}");

        var kp2 = KeyPair.FromSeed(seed.ToCharArray());
        Assert.Equal(kp1.GetPublicKey(), kp2.GetPublicKey());
        output.WriteLine($"pk={kp1.GetPublicKey()}");

        var kp3 = KeyPair.FromPublicKey(publicKey.ToCharArray());
        Assert.Equal(kp1.GetPublicKey(), kp3.GetPublicKey());
        output.WriteLine($"pk={kp3.GetPublicKey()}");

        // Using generated seeds
        var encodedSeed = "SOAELH6NJCEK4HST5644G4HK7TOAFZGRRJHNM4EUKUY7PPNDLIKO5IH4JM";
        var encodedPublicKey = "ODPWIBQJVIQ42462QAFI2RKJC4RZHCQSIVPRDDHWFCJAP52NRZK6Z2YC";

        var kp4 = KeyPair.FromSeed(encodedSeed);
        Assert.Equal(encodedPublicKey, kp4.GetPublicKey());
        output.WriteLine($"pk={kp4.GetPublicKey()}");

        var kp5 = KeyPair.FromPublicKey(encodedPublicKey);
        Assert.Equal(encodedPublicKey, kp5.GetPublicKey());

        var message = new ReadOnlyMemory<byte>([42, 43, 44]);
        var signature = new Memory<byte>(new byte[64]);
        kp4.Sign(message, signature);
        Assert.True(kp5.Verify(message, signature));

        var corrupt = new ReadOnlyMemory<byte>([43, 44]);
        Assert.False(kp5.Verify(corrupt, signature));
    }

    [Fact]
    public void DecodePubCurveKey_returns_exactly_32_bytes()
    {
        var kp = KeyPair.CreatePair(PrefixByte.Curve);
        var decoded = KeyPair.DecodePubCurveKey(kp.GetPublicKey());
        Assert.Equal(32, decoded.Length);
    }

    [Fact]
    public void DecodePubCurveKey_returns_32_bytes_for_multiple_keys()
    {
        // Verify across several independently generated keys
        for (var i = 0; i < 10; i++)
        {
            var kp = KeyPair.CreatePair(PrefixByte.Curve);
            var decoded = KeyPair.DecodePubCurveKey(kp.GetPublicKey());
            Assert.Equal(32, decoded.Length);
        }
    }

    [Fact]
    public void DecodePubCurveKey_deterministic_for_known_seed()
    {
        var kp = KeyPair.FromSeed("SXAD4F52S2XAJTJ3TGDJ4VXQVW7TU35XJUSVKF25ZRXIWCIUK6NLANRHVY".ToCharArray());
        var decoded1 = KeyPair.DecodePubCurveKey(kp.GetPublicKey());
        var decoded2 = KeyPair.DecodePubCurveKey(kp.GetPublicKey());
        Assert.Equal(decoded1, decoded2);
        Assert.Equal(32, decoded1.Length);
    }

    [Fact]
    public void DecodePubCurveKey_matches_known_public_key()
    {
        // Known seed/public key pair from existing tests
        var kp = KeyPair.FromSeed("SXANLPW5OPP62ISXMPTH26DBYM4BGT3U6P2FEALGW3BZAVXQRWCX3KH2ZM".ToCharArray());
        Assert.Equal("XBIGHMCJSHWYFW6ZY4WWONQ3FRIS5A3OQAUMPPKYBNKRYQTVX4PEAIZA", kp.GetPublicKey());
        var decoded = KeyPair.DecodePubCurveKey(kp.GetPublicKey());
        Assert.Equal(32, decoded.Length);
    }

    [Fact]
    public void DecodePubCurveKey_does_not_include_prefix_byte()
    {
        var kp = KeyPair.CreatePair(PrefixByte.Curve);
        var publicKey = kp.GetPublicKey();

        // Decode the full base32 to get raw bytes including prefix and CRC
        var rawLen = Base32.GetDataLength(publicKey.ToCharArray());
        var raw = new byte[rawLen];
        Base32.FromBase32(publicKey.ToCharArray(), raw);

        // First byte is the prefix
        var prefixByte = raw[0];
        Assert.Equal((byte)PrefixByte.Curve, prefixByte);

        // DecodePubCurveKey should return bytes [1..33), not include prefix or CRC
        var decoded = KeyPair.DecodePubCurveKey(publicKey);
        Assert.Equal(raw.AsSpan().Slice(1, 32).ToArray(), decoded);
    }

    [Fact]
    public void DecodePubCurveKey_does_not_include_crc_bytes()
    {
        var kp = KeyPair.CreatePair(PrefixByte.Curve);
        var publicKey = kp.GetPublicKey();

        // Get the raw decoded bytes
        var rawLen = Base32.GetDataLength(publicKey.ToCharArray());
        var raw = new byte[rawLen];
        Base32.FromBase32(publicKey.ToCharArray(), raw);

        // Decoded key should be exactly raw[1..33) — the 32-byte key without prefix or CRC
        var decoded = KeyPair.DecodePubCurveKey(publicKey);
        Assert.Equal(32, decoded.Length);
        Assert.Equal(raw.AsSpan().Slice(1, 32).ToArray(), decoded);
    }

    [Fact]
    public void DecodePubCurveKey_round_trips_with_seal_open()
    {
        var kp1 = KeyPair.FromSeed("SXAD4F52S2XAJTJ3TGDJ4VXQVW7TU35XJUSVKF25ZRXIWCIUK6NLANRHVY".ToCharArray());
        var kp2 = KeyPair.CreatePair(PrefixByte.Curve);

        var message = new byte[] { 1, 2, 3, 4, 5 };
        var sealed1 = kp1.Seal(message, kp2.GetPublicKey());
        var opened = kp2.Open(sealed1, kp1.GetPublicKey());
        Assert.Equal(message, opened);
    }

    [Fact]
    public void DecodePubCurveKey_rejects_non_curve_key()
    {
        // A valid User public key has the same decoded length but wrong prefix
        var kp = KeyPair.CreatePair(PrefixByte.User);
        var ex = Assert.Throws<NKeysException>(() => KeyPair.DecodePubCurveKey(kp.GetPublicKey()));
        Assert.Equal("Not a valid curve key", ex.Message);
    }

    [Fact]
    public void DecodePubCurveKey_rejects_too_short()
    {
        var ex = Assert.Throws<NKeysException>(() => KeyPair.DecodePubCurveKey("XAAA"));
        Assert.Equal("Not a valid curve key", ex.Message);
    }

    [Fact]
    public void DecodePubCurveKey_rejects_too_long()
    {
        // Take a valid key and append extra base32 characters
        var kp = KeyPair.CreatePair(PrefixByte.Curve);
        var tooLong = kp.GetPublicKey() + "AAAAAAAAAA";
        Assert.Throws<NKeysException>(() => KeyPair.DecodePubCurveKey(tooLong));
    }

    [Fact]
    public void DecodePubCurveKey_rejects_empty_string()
    {
        Assert.ThrowsAny<Exception>(() => KeyPair.DecodePubCurveKey(string.Empty));
    }

    [Fact]
    public void DecodePubCurveKey_rejects_corrupted_crc()
    {
        var kp = KeyPair.CreatePair(PrefixByte.Curve);
        var publicKey = kp.GetPublicKey();

        // Corrupt a character in the middle of the key
        var chars = publicKey.ToCharArray();
        chars[10] = chars[10] == 'A' ? 'B' : 'A';
        var corrupted = new string(chars);

        var ex = Assert.Throws<NKeysException>(() => KeyPair.DecodePubCurveKey(corrupted));
        Assert.Equal("Invalid CRC", ex.Message);
    }

    [Fact]
    public void DecodePubCurveKey_rejects_invalid_base32_characters()
    {
        var kp = KeyPair.CreatePair(PrefixByte.Curve);
        var publicKey = kp.GetPublicKey();

        // Replace with invalid base32 chars (lowercase, digits 0/1/8/9, symbols)
        var chars = publicKey.ToCharArray();
        chars[5] = '!';
        Assert.Throws<ArgumentException>(() => KeyPair.DecodePubCurveKey(new string(chars)));
    }

    [Fact]
    public void DecodePubCurveKey_different_keys_produce_different_results()
    {
        var kp1 = KeyPair.CreatePair(PrefixByte.Curve);
        var kp2 = KeyPair.CreatePair(PrefixByte.Curve);

        var decoded1 = KeyPair.DecodePubCurveKey(kp1.GetPublicKey());
        var decoded2 = KeyPair.DecodePubCurveKey(kp2.GetPublicKey());

        Assert.NotEqual(decoded1, decoded2);
    }

    [Fact]
    public void DecodePubCurveKey_cross_validates_with_go_test_data()
    {
        // Use the Go-generated test data to verify decode produces
        // keys that work correctly in seal/open operations
        var json = JsonNode.Parse(File.ReadAllText("test_data.json"));
        foreach (var data in json!["xkeys"]!.AsArray())
        {
            var pk1 = data!["pk1"]!.GetValue<string>();
            var pk2 = data!["pk2"]!.GetValue<string>();

            var decoded1 = KeyPair.DecodePubCurveKey(pk1);
            var decoded2 = KeyPair.DecodePubCurveKey(pk2);

            Assert.Equal(32, decoded1.Length);
            Assert.Equal(32, decoded2.Length);
        }
    }

    [Fact]
    public void DecodePubCurveKey_blackbox_seal_open_with_decoded_key()
    {
        // Black box: if DecodePubCurveKey returns the correct raw key,
        // then encrypting for that key and decrypting must round-trip
        var sender = KeyPair.CreatePair(PrefixByte.Curve);
        var receiver = KeyPair.CreatePair(PrefixByte.Curve);

        var payloads = new byte[][]
        {
            Array.Empty<byte>(),
            new byte[] { 0 },
            new byte[] { 0xFF },
            Encoding.UTF8.GetBytes("hello world"),
            new byte[1024],
            new byte[8192],
        };

        foreach (var payload in payloads)
        {
            var sealed1 = sender.Seal(payload, receiver.GetPublicKey());
            var opened = receiver.Open(sealed1, sender.GetPublicKey());
            Assert.Equal(payload, opened);
        }
    }

    [Fact]
    public void DecodePubCurveKey_blackbox_two_parties_cross_seal()
    {
        // Black box: both parties can seal for each other and open
        var alice = KeyPair.CreatePair(PrefixByte.Curve);
        var bob = KeyPair.CreatePair(PrefixByte.Curve);
        var message = Encoding.UTF8.GetBytes("secret message");

        // Alice seals for Bob
        var sealedForBob = alice.Seal(message, bob.GetPublicKey());
        Assert.Equal(message, bob.Open(sealedForBob, alice.GetPublicKey()));

        // Bob seals for Alice
        var sealedForAlice = bob.Seal(message, alice.GetPublicKey());
        Assert.Equal(message, alice.Open(sealedForAlice, bob.GetPublicKey()));
    }

    [Fact]
    public void DecodePubCurveKey_blackbox_wrong_sender_fails_open()
    {
        // Black box: opening with wrong sender key must fail
        var alice = KeyPair.CreatePair(PrefixByte.Curve);
        var bob = KeyPair.CreatePair(PrefixByte.Curve);
        var eve = KeyPair.CreatePair(PrefixByte.Curve);

        var sealed1 = alice.Seal(Encoding.UTF8.GetBytes("secret"), bob.GetPublicKey());

        // Bob tries to open with Eve's public key as sender — must fail
        Assert.Throws<NKeysException>(() => bob.Open(sealed1, eve.GetPublicKey()));
    }

    [Fact]
    public void DecodePubCurveKey_blackbox_wrong_receiver_fails_open()
    {
        // Black box: wrong receiver cannot open
        var alice = KeyPair.CreatePair(PrefixByte.Curve);
        var bob = KeyPair.CreatePair(PrefixByte.Curve);
        var eve = KeyPair.CreatePair(PrefixByte.Curve);

        var sealed1 = alice.Seal(Encoding.UTF8.GetBytes("secret"), bob.GetPublicKey());

        // Eve tries to open something meant for Bob
        Assert.Throws<NKeysException>(() => eve.Open(sealed1, alice.GetPublicKey()));
    }

    [Fact]
    public void DecodePubCurveKey_blackbox_tampered_ciphertext_fails()
    {
        var alice = KeyPair.CreatePair(PrefixByte.Curve);
        var bob = KeyPair.CreatePair(PrefixByte.Curve);

        var sealed1 = alice.Seal(Encoding.UTF8.GetBytes("secret"), bob.GetPublicKey());

        // Flip a byte in the encrypted payload (after version + nonce header)
        sealed1[30] ^= 0xFF;

        Assert.Throws<NKeysException>(() => bob.Open(sealed1, alice.GetPublicKey()));
    }

    [Fact]
    public void DecodePubCurveKey_blackbox_each_seal_produces_different_ciphertext()
    {
        // Black box: nonce randomization means same plaintext encrypts differently
        var alice = KeyPair.CreatePair(PrefixByte.Curve);
        var bob = KeyPair.CreatePair(PrefixByte.Curve);
        var message = Encoding.UTF8.GetBytes("hello");

        var sealed1 = alice.Seal(message, bob.GetPublicKey());
        var sealed2 = alice.Seal(message, bob.GetPublicKey());

        Assert.NotEqual(sealed1, sealed2);

        // But both decrypt to the same message
        Assert.Equal(message, bob.Open(sealed1, alice.GetPublicKey()));
        Assert.Equal(message, bob.Open(sealed2, alice.GetPublicKey()));
    }

    [Theory]
    [InlineData(0)]
    [InlineData(28)]
    [InlineData(29)]
    [InlineData(43)]
    public void Open_rejects_short_input(int length)
    {
        var kp = KeyPair.CreatePair(PrefixByte.Curve);
        var input = new byte[length];

        // Fill with valid version header if long enough
        if (length >= 4)
        {
            input[0] = (byte)'x';
            input[1] = (byte)'k';
            input[2] = (byte)'v';
            input[3] = (byte)'1';
        }

        var ex = Assert.Throws<NKeysException>(() => kp.Open(input, kp.GetPublicKey()));
        Assert.Equal("Encrypted input is not valid", ex.Message);
    }

    [Fact]
    public void Public_key_does_not_have_seed_nor_secret_key()
    {
        var encodedPublicKey = "ODPWIBQJVIQ42462QAFI2RKJC4RZHCQSIVPRDDHWFCJAP52NRZK6Z2YC";

        var pair = KeyPair.FromPublicKey(encodedPublicKey);
        Assert.Equal(encodedPublicKey, pair.GetPublicKey());

        Assert.Throws<NKeysException>(() => pair.GetSeed());
        Assert.Throws<NKeysException>(() => pair.Sign(default, default));
    }
}
