name: Test

on:
  pull_request: {}
  push:
    branches:
    - main

jobs:
  dotnet:
    name: dotnet
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
              6.x
              8.x

      - name: Build
        run: dotnet build -c Debug

      - name: Test Core
        run: dotnet test -c Debug --no-build --logger:"console;verbosity=normal"

      - name: Check Native AOT
        shell: bash
        run: |
            export exe_file=NATS.NKeys.CheckNativeAot
            export exe_type=ELF
            export dotnet_runtime_id=linux-x64

            if [ "${{ matrix.os }}" = "windows-latest" ]; then
              export exe_file=NATS.NKeys.CheckNativeAot.exe
              export exe_type=PE32
              export dotnet_runtime_id=win-x64
              file NATS.NKeys.CheckNativeAot.exe | grep PE32 || exit 1
            elif [ "${{ matrix.os }}" = "macos-latest" ]; then
              export dotnet_runtime_id=osx-x64
              export exe_type=Mach-O
            fi

            cd NATS.NKeys.CheckNativeAot
            rm -rf bin obj
            dotnet publish -r $dotnet_runtime_id -c Release -o dist | tee output.txt

            # check for warnings
            grep -i warning output.txt && exit 1

            cd dist
            ls -lh

            file $exe_file
            file $exe_file | grep $exe_type || exit 1

            # Can't be less than a meg and not more than 10 megs.
            # Fairly arbitrary, but we want to make sure executable size
            # is reasonable so we can be somewhat sure AOT compilation
            # happened correctly.
            export filesize=0

            if [ "${{ matrix.os }}" = "windows-latest" ]; then
              export filesize=$(stat -c %s $exe_file)
            elif [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
              export filesize=$(stat -c %s $exe_file)
            elif [ "${{ matrix.os }}" = "macos-latest" ]; then
              export filesize=$(stat -f %z $exe_file)
            fi

            echo "File size: $filesize bytes"
            if [ $filesize -lt 1048576 ]; then
              echo "File is less than 1MB."
              exit 1
            fi
            if [ $filesize -gt 10485760 ]; then
              echo "File is more than 10MB."
              exit 1
            fi

            ./$exe_file | tee | grep PASS || exit 1
